# Generated by Django 5.2.5 on 2026-08-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Unnamed Project', max_length=200)),
                ('project_size', models.CharField(max_length=50)),
                ('team_size', models.IntegerField()),
                ('project_duration', models.IntegerField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('project_complexity', models.CharField(max_length=50)),
                ('requirements_stability', models.CharField(max_length=50)),
                ('requirement_changes', models.IntegerField()),
                ('communication_level', models.CharField(max_length=50)),
                ('project_management_quality', models.CharField(max_length=50)),
                ('resource_availability', models.CharField(max_length=50)),
                ('team_experience', models.CharField(max_length=50)),
                ('technical_expertise', models.CharField(max_length=50)),
                ('testing_level', models.CharField(max_length=50)),
                ('quality_factors', models.CharField(max_length=50)),
                ('previous_defects', models.IntegerField()),
                ('risk_level', models.CharField(max_length=30)),
                ('risk_category', models.CharField(max_length=30)),
                ('risk_probability', models.FloatField()),
                ('confidence', models.FloatField()),
                ('main_contributing_factors', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
